In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
#imports

In [2]:
salaries_03_to_18 = pd.read_csv('./datasets/NBASalaryData03-17.csv')
twenty_salary_cond = pd.read_csv('./datasets/twenty_salary_cond.csv')

In [3]:
eleven_salary = salaries_03_to_18[salaries_03_to_18.season == '2010-2011']
twelve_salary = salaries_03_to_18[salaries_03_to_18.season == '2011-2012']
thirtheen_salary = salaries_03_to_18[salaries_03_to_18.season == '2012-2013']
fourteen_salary = salaries_03_to_18[salaries_03_to_18.season == '2013-2014']
fifteen_salary = salaries_03_to_18[salaries_03_to_18.season == '2014-2015']
sixteen_salary = salaries_03_to_18[salaries_03_to_18.season == '2015-2016']
seventeen_salary = salaries_03_to_18[salaries_03_to_18.season == '2016-2017']
eighteen_salary = salaries_03_to_18[salaries_03_to_18.season == '2017-2018']
#Breaking up salary by year

In [4]:
eleven_salary.to_csv('./datasets/eleven_salary.csv', index = False)
twelve_salary.to_csv('./datasets/twelve_salary.csv', index = False)
thirtheen_salary.to_csv('./datasets/thirtheen_salary.csv', index = False)
fourteen_salary.to_csv('./datasets/fourteen_salary.csv', index = False)
fifteen_salary.to_csv('./datasets/fifteen_salary.csv', index = False)
sixteen_salary.to_csv('./datasets/sixteen_salary.csv', index = False)
seventeen_salary.to_csv('./datasets/seventeen_salary.csv', index = False)
eighteen_salary.to_csv('./datasets/eighteen_salary.csv', index = False)

In [5]:
twenty_stats = pd.read_csv('./datasets/twenty_STATS.csv')
nineteen_stats = pd.read_csv('./datasets/nineteen_STATS.csv')
eighteen_stats =  pd.read_csv('./datasets/eighteen_STATS.csv')
seventeen_stats = pd.read_csv('./datasets/seventeen_STATS.csv')
sixteen_stats = pd.read_csv('./datasets/sixteen_STATS.csv')
OLD_fifteen_stats = pd.read_csv('./datasets/fifteen_STATS.csv')
fourteen_stats = pd.read_csv('./datasets/fourteen_STATS.csv')
thirteen_stats = pd.read_csv('./datasets/thirteen_STATS.csv')
twelve_stats = pd.read_csv('./datasets/twelve_STATS.csv')
eleven_stats = pd.read_csv('./datasets/eleven_STATS.csv')

fifteen_stats = pd.read_csv('./datasets/new_fifteen_stats.csv')

#Loading in data

In [6]:
s=pd.concat([twenty_stats,nineteen_stats,eighteen_stats,seventeen_stats],axis=0)

In [7]:
new_s = s[s['Player'].map(s['Player'].value_counts()) == 4]
new_s

#Here, I tried grouping by players who had participated in the last 4 seasons instead of 5
#I did not end up using 4 year increments because the difference in amount of data was minimal and results were worse

,Rk,Player,Season,Pos,Age,Tm,G,GS,MP,FG,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1.0,Steven Adams,19-20,C,26.0,OKC,63.0,63.0,26.7,4.5,...,0.582,3.3,6.0,9.3,2.3,0.8,1.1,1.5,1.9,10.9
2,3.0,LaMarcus Aldridge,19-20,C,34.0,SAS,53.0,53.0,33.1,7.4,...,0.827,1.9,5.5,7.4,2.4,0.7,1.6,1.4,2.4,18.9
8,9.0,Al-Farouq Aminu,19-20,PF,29.0,ORL,18.0,2.0,21.1,1.4,...,0.655,1.3,3.5,4.8,1.2,1.0,0.4,0.9,1.5,4.3
9,10.0,Justin Anderson,19-20,SF,26.0,BRK,10.0,1.0,10.7,1.0,...,0.500,0.1,2.0,2.1,0.8,0.0,0.6,0.4,1.3,2.8
10,11.0,Kyle Anderson,19-20,PF,26.0,MEM,67.0,28.0,19.9,2.3,...,0.667,0.9,3.4,4.3,2.4,0.8,0.6,1.0,1.7,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,477.0,Delon Wright,16-17,PG,24.0,TOR,27.0,0.0,16.5,1.8,...,0.764,0.6,1.2,1.8,2.1,1.0,0.4,0.9,1.1,5.6
480,481.0,Thaddeus Young,16-17,PF,28.0,IND,74.0,74.0,30.2,4.9,...,0.523,1.8,4.3,6.1,1.6,1.5,0.4,1.3,1.8,11.0
481,482.0,Cody Zeller,16-17,C,24.0,CHO,62.0,58.0,27.8,4.1,...,0.679,2.2,4.4,6.5,1.6,1.0,0.9,1.0,3.0,10.3
482,483.0,Tyler Zeller,16-17,C,27.0,BOS,51.0,5.0,10.3,1.5,...,0.564,0.8,1.6,2.4,0.8,0.1,0.4,0.4,1.2,3.5
485,486.0,Ivica Zubac,16-17,C,19.0,LAL,38.0,11.0,16.0,3.3,...,0.653,1.1,3.1,4.2,0.8,0.4,0.9,0.8,1.7,7.5

In [8]:
aggregation_functions = {'Rk': 'first', 'Season': 'first', 'Pos': 'first', 'Age': 'mean', 'Tm': 'first', 'G': 'mean', 'GS': 'mean', 'MP': 'mean', 'FG': 'mean',
       'FGA': 'mean', 'FG%': 'mean', '3P': 'mean', '3PA': 'mean', '3P%': 'mean', '2P': 'mean', '2PA': 'mean', '2P%': 'mean', 'eFG%': 'mean', 
        'FT': 'mean', 'FTA': 'mean', 'FT%': 'mean', 'ORB': 'mean', 'DRB': 'mean', 'TRB': 'mean', 'AST': 'mean', 'STL': 'mean',
        'BLK': 'mean', 'TOV': 'mean', 'PF': 'mean',
       'PTS': 'mean'}
df_new = new_s.groupby(new_s['Player']).aggregate(aggregation_functions)
df_new
#Finding averages of all of the players over this five year span

,Rk,Season,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
Player,,,,,,,,,,,,,,,,,,,,,
Aaron Gordon,178.0,19-20,PF,22.5,ORL,69.50,67.25,31.975,5.700,12.875,...,0.70550,1.600,5.400,7.025,2.900,0.825,0.650,1.650,2.075,15.175
Al Horford,228.0,19-20,C,31.5,PHI,68.75,67.25,30.775,5.300,10.875,...,0.79175,1.525,5.400,6.925,4.475,0.775,1.150,1.550,1.975,13.100
Al-Farouq Aminu,9.0,19-20,PF,27.5,ORL,57.25,43.75,27.125,2.725,7.025,...,0.74150,1.350,5.475,6.825,1.325,0.975,0.525,1.100,1.750,7.925
Alec Burks,80.0,19-20,SG,26.5,TOT,59.00,11.00,20.025,3.250,7.850,...,0.83550,0.475,2.975,3.475,1.650,0.625,0.200,1.025,1.425,9.550
Alex Len,293.0,19-20,C,24.5,TOT,69.50,22.50,19.550,3.375,6.425,...,0.67525,2.100,4.275,6.350,0.950,0.425,1.000,1.175,2.575,8.900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Willie Cauley-Stein,94.0,19-20,C,24.5,TOT,70.75,49.75,23.625,4.250,7.925,...,0.61125,1.675,4.750,6.425,1.800,0.975,0.800,1.025,2.375,10.000
Willy Hernangómez,214.0,19-20,C,23.5,CHO,52.25,6.50,13.700,2.575,4.875,...,0.67625,1.775,3.325,5.125,0.975,0.400,0.325,1.025,1.525,6.675
Wilson Chandler,96.0,19-20,SF,30.5,BRK,57.75,35.00,26.675,3.550,8.075,...,0.77225,1.025,4.025,5.050,1.700,0.575,0.400,1.175,2.300,9.400
Yogi Ferrell,156.0,19-20,PG,24.5,SAC,62.25,13.25,19.850,2.775,6.575,...,0.84500,0.250,1.750,1.975,2.375,0.650,0.125,0.925,1.400,7.625
Zach LaVine,286.0,19-20,SG,22.5,CHI,48.50,48.25,33.450,7.500,16.975,...,0.82075,0.525,3.650,4.200,3.675,1.100,0.325,2.600,2.225,21.200

In [9]:
_17_to_20_with_sal = pd.merge(left=df_new, right=twenty_salary_cond, how='left', on='Player')

In [10]:
_17_to_20_with_sal['Player'].duplicated().value_counts()

False    260
True      28
Name: Player, dtype: int64

In [11]:
_17_to_20_with_sal = _17_to_20_with_sal.drop_duplicates(subset=['Player'], keep='first')
_17_to_20_with_sal.head()

,Player,Rk,Season,Pos,Age,Tm,G,GS,MP,FG,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,2019-20
0,Aaron Gordon,178.0,19-20,PF,22.5,ORL,69.50,67.25,31.975,5.700,...,1.600,5.400,7.025,2.900,0.825,0.650,1.650,2.075,15.175,"$19,863,636"
1,Al Horford,228.0,19-20,C,31.5,PHI,68.75,67.25,30.775,5.300,...,1.525,5.400,6.925,4.475,0.775,1.150,1.550,1.975,13.100,"$28,000,000"
2,Al-Farouq Aminu,9.0,19-20,PF,27.5,ORL,57.25,43.75,27.125,2.725,...,1.350,5.475,6.825,1.325,0.975,0.525,1.100,1.750,7.925,"$9,258,000"
3,Alec Burks,80.0,19-20,SG,26.5,TOT,59.00,11.00,20.025,3.250,...,0.475,2.975,3.475,1.650,0.625,0.200,1.025,1.425,9.550,"$2,320,044"
4,Alex Len,293.0,19-20,C,24.5,TOT,69.50,22.50,19.550,3.375,...,2.100,4.275,6.350,0.950,0.425,1.000,1.175,2.575,8.900,"$4,160,000"

In [12]:
_17_to_20_with_sal.isnull().sum()

Player     0
Rk         0
Season     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         0
FGA        0
FG%        0
3P         0
3PA        0
3P%        0
2P         0
2PA        0
2P%        0
eFG%       0
FT         0
FTA        0
FT%        0
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
2019-20    8
dtype: int64

In [13]:
_17_to_20_with_sal = _17_to_20_with_sal.dropna()

In [14]:
_17_to_20_with_sal.shape

(252, 32)

In [15]:
_17_to_20_with_sal['2019-20'] = _17_to_20_with_sal['2019-20'].str.replace(',', '')
#Taking steps to turn column into integer

In [16]:
_17_to_20_with_sal['2019-20'] = _17_to_20_with_sal['2019-20'].str.replace('$', '')

In [17]:
_17_to_20_with_sal['2019-20'] = _17_to_20_with_sal['2019-20'].astype(int)
#Turning salary into an integer

In [18]:
_17_to_20_with_sal.corr()['2019-20'].sort_values(ascending=False)

2019-20    1.000000
PTS        0.769917
FG         0.756655
FGA        0.744345
MP         0.728757
FT         0.711148
FTA        0.701033
GS         0.690506
2PA        0.682875
TOV        0.682009
2P         0.669511
AST        0.591008
STL        0.560910
DRB        0.559780
TRB        0.487346
3PA        0.447394
3P         0.438508
PF         0.373891
G          0.303399
BLK        0.300565
FT%        0.266914
ORB        0.243670
3P%        0.125528
eFG%       0.104810
FG%        0.101789
Age        0.088307
2P%        0.084514
Rk        -0.007524
Name: 2019-20, dtype: float64

In [19]:
_17_to_20_with_sal.to_csv('./datasets/seventeen_to_twenty_with_sal.csv', index=False)

In [20]:
def condense_salary(year):
    year = year[['player', 'salary']]
    
    return year

#Function to reduce the salary columns so that they are ready for merging

In [21]:
eleven_salary = condense_salary(eleven_salary)
twelve_salary = condense_salary(twelve_salary)
thirtheen_salary = condense_salary(thirtheen_salary)
fourteen_salary = condense_salary(fourteen_salary)
fifteen_salary = condense_salary(fifteen_salary)
sixteen_salary = condense_salary(sixteen_salary)
seventeen_salary = condense_salary(seventeen_salary)
eighteen_salary = condense_salary(eighteen_salary)

In [22]:
eleven_salary = eleven_salary.rename(columns={'player': 'Player'})
twelve_salary = twelve_salary.rename(columns={'player': 'Player'})
thirtheen_salary = thirtheen_salary.rename(columns={'player': 'Player'})
fourteen_salary = fourteen_salary.rename(columns={'player': 'Player'})
fifteen_salary = fifteen_salary.rename(columns={'player': 'Player'})
sixteen_salary = sixteen_salary.rename(columns={'player': 'Player'})
seventeen_salary = seventeen_salary.rename(columns={'player': 'Player'})
eighteen_salary = eighteen_salary.rename(columns={'player': 'Player'})

#Since the column in the statistics dataframe is called 'Player', changing the column in the salary dataframe
#will make it easier to merge

# Merging 11-15 stats with salary from '15

In [23]:
s=pd.concat([fifteen_stats, fourteen_stats, thirteen_stats, twelve_stats, eleven_stats],axis=0)

In [24]:
new_s = s[s['Player'].map(s['Player'].value_counts()) == 5]
new_s

,Rk,Player,Season,Pos,Age,Tm,G,GS,MP,FG,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
3,4,Jeff Adrien,14-15,PF,28,MIN,17,0,12.6,1.1,...,0.579,1.4,3.2,4.5,0.9,0.2,0.5,0.5,1.8,3.5
4,5,Arron Afflalo,14-15,SG,29,TOT,78,72,32.1,4.8,...,0.843,0.3,2.8,3.2,1.7,0.5,0.1,1.5,2.1,13.3
5,6,Alexis Ajinça,14-15,C,26,NOP,68,8,14.1,2.7,...,0.818,1.5,3.1,4.6,0.7,0.3,0.8,1.0,2.2,6.5
7,8,Cole Aldrich,14-15,C,26,NYK,61,16,16.0,2.4,...,0.781,1.7,3.9,5.5,1.2,0.6,1.1,1.0,2.0,5.5
8,9,LaMarcus Aldridge,14-15,PF,29,POR,71,71,35.4,9.3,...,0.845,2.5,7.7,10.2,1.7,0.7,1.0,1.7,1.8,23.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613,444,Terrence Williams,10-11,SG,23,NJN,10,0,20.6,2.9,...,0.500,0.3,3.3,3.6,3.1,0.5,0.0,2.5,2.1,6.7
614,444,Terrence Williams,10-11,SG,23,HOU,11,0,7.6,1.3,...,0.818,0.1,1.3,1.4,0.6,0.4,0.0,0.7,0.4,3.5
620,448,Dorell Wright,10-11,SF,25,GSW,82,82,38.4,5.9,...,0.789,1.1,4.2,5.3,3.0,1.5,0.8,1.6,2.1,16.4
622,450,Nick Young,10-11,SG,25,WAS,64,40,31.8,6.4,...,0.816,0.4,2.3,2.7,1.2,0.7,0.3,1.4,2.3,17.4
624,452,Thaddeus Young,10-11,PF,22,PHI,82,1,26.0,5.6,...,0.707,1.9,3.4,5.3,1.0,1.1,0.3,1.2,2.1,12.7

In [25]:
aggregation_functions = {'Rk': 'first', 'Season': 'first', 'Pos': 'first', 'Age': 'mean', 'Tm': 'first', 'G': 'mean', 'GS': 'mean', 'MP': 'mean', 'FG': 'mean',
       'FGA': 'mean', 'FG%': 'mean', '3P': 'mean', '3PA': 'mean', '3P%': 'mean', '2P': 'mean', '2PA': 'mean', '2P%': 'mean', 'eFG%': 'mean', 
        'FT': 'mean', 'FTA': 'mean', 'FT%': 'mean', 'ORB': 'mean', 'DRB': 'mean', 'TRB': 'mean', 'AST': 'mean', 'STL': 'mean',
        'BLK': 'mean', 'TOV': 'mean', 'PF': 'mean',
       'PTS': 'mean'}
df_new = new_s.groupby(new_s['Player']).aggregate(aggregation_functions)
df_new

,Rk,Season,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
Player,,,,,,,,,,,,,,,,,,,,,
A.J. Price,373,14-15,PG,26.0,TOT,41.0,4.6,13.44,1.82,4.90,...,0.5848,0.24,1.02,1.28,2.02,0.40,0.02,0.74,0.80,4.96
Al Horford,222,14-15,C,26.0,ATL,53.4,53.4,33.48,6.94,12.58,...,0.7232,2.28,6.14,8.42,2.94,0.92,1.24,1.70,2.02,15.78
Al Jefferson,236,14-15,C,28.0,CHO,71.8,71.0,33.72,8.28,16.68,...,0.7300,2.14,7.40,9.54,1.98,0.80,1.42,1.26,2.42,18.80
Al-Farouq Aminu,12,14-15,SF,22.0,DAL,75.4,34.8,22.32,2.44,5.54,...,0.7280,1.44,3.84,5.30,1.06,0.94,0.56,1.20,1.86,6.34
Alexis Ajinça,6,14-15,C,23.4,NOP,38.4,8.4,11.92,2.00,4.10,...,0.7552,0.94,2.28,3.20,0.44,0.32,0.66,0.68,2.28,4.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Willie Green,189,14-15,SG,31.0,ORL,61.8,17.2,17.94,2.62,6.04,...,0.8008,0.26,1.32,1.56,0.96,0.44,0.16,0.68,1.58,6.70
Xavier Henry,209,14-15,SF,21.0,LAL,37.0,4.6,14.80,1.72,4.38,...,0.6230,0.38,1.24,1.66,0.62,0.50,0.12,0.66,1.30,5.14
Zach Randolph,380,14-15,PF,31.0,MEM,65.8,61.4,32.72,6.48,13.56,...,0.7348,3.56,6.88,10.40,2.00,0.82,0.26,1.98,2.38,16.12
Zaza Pachulia,354,14-15,C,28.0,MIL,63.0,30.8,22.90,2.52,5.42,...,0.7772,2.42,3.92,6.34,1.72,0.78,0.32,1.42,2.48,6.82
Ömer Aşık,24,14-15,C,26.0,NOP,70.8,35.8,20.62,2.22,4.20,...,0.5444,2.40,5.30,7.68,0.64,0.40,0.86,1.28,2.04,5.82

In [27]:
_11_to_15_with_sal = pd.merge(left=df_new, right=fifteen_salary, how='left', on='Player')

In [29]:
_11_to_15_with_sal

,Player,Rk,Season,Pos,Age,Tm,G,GS,MP,FG,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,salary
0,A.J. Price,373,14-15,PG,26.0,TOT,41.0,4.6,13.44,1.82,...,0.24,1.02,1.28,2.02,0.40,0.02,0.74,0.80,4.96,53838.0
1,Al Horford,222,14-15,C,26.0,ATL,53.4,53.4,33.48,6.94,...,2.28,6.14,8.42,2.94,0.92,1.24,1.70,2.02,15.78,12000000.0
2,Al Jefferson,236,14-15,C,28.0,CHO,71.8,71.0,33.72,8.28,...,2.14,7.40,9.54,1.98,0.80,1.42,1.26,2.42,18.80,13500000.0
3,Al-Farouq Aminu,12,14-15,SF,22.0,DAL,75.4,34.8,22.32,2.44,...,1.44,3.84,5.30,1.06,0.94,0.56,1.20,1.86,6.34,981084.0
4,Alexis Ajinça,6,14-15,C,23.4,NOP,38.4,8.4,11.92,2.00,...,0.94,2.28,3.20,0.44,0.32,0.66,0.68,2.28,4.86,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,Willie Green,189,14-15,SG,31.0,ORL,61.8,17.2,17.94,2.62,...,0.26,1.32,1.56,0.96,0.44,0.16,0.68,1.58,6.70,1448490.0
203,Xavier Henry,209,14-15,SF,21.0,LAL,37.0,4.6,14.80,1.72,...,0.38,1.24,1.66,0.62,0.50,0.12,0.66,1.30,5.14,1082000.0
204,Zach Randolph,380,14-15,PF,31.0,MEM,65.8,61.4,32.72,6.48,...,3.56,6.88,10.40,2.00,0.82,0.26,1.98,2.38,16.12,16500000.0
205,Zaza Pachulia,354,14-15,C,28.0,MIL,63.0,30.8,22.90,2.52,...,2.42,3.92,6.34,1.72,0.78,0.32,1.42,2.48,6.82,5200000.0
206,Ömer Aşık,24,14-15,C,26.0,NOP,70.8,35.8,20.62,2.22,...,2.40,5.30,7.68,0.64,0.40,0.86,1.28,2.04,5.82,NaN

# Merging 12-16 stats with salary from '16

In [29]:
s=pd.concat([sixteen_stats, fifteen_stats, fourteen_stats, thirteen_stats, twelve_stats],axis=0)

In [30]:
new_s = s[s['Player'].map(s['Player'].value_counts()) == 5]
new_s

,Rk,Player,Season,Pos,Age,Tm,G,GS,MP,FG,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
3,4,Arron Afflalo,15-16,SG,30,NYK,71,57,33.4,5.0,...,0.840,0.3,3.4,3.7,2.0,0.4,0.1,1.2,2.0,12.8
5,6,Cole Aldrich,15-16,C,27,LAC,60,5,13.3,2.2,...,0.714,1.4,3.4,4.8,0.8,0.8,1.1,1.1,2.3,5.5
6,7,LaMarcus Aldridge,15-16,PF,30,SAS,74,74,30.6,7.2,...,0.858,2.4,6.2,8.5,1.5,0.5,1.1,1.3,2.0,18.0
8,9,Lavoy Allen,15-16,PF,26,IND,79,28,20.2,2.4,...,0.630,2.1,3.3,5.4,1.0,0.3,0.5,0.9,1.9,5.4
9,10,Tony Allen,15-16,SG,34,MEM,64,57,25.3,3.4,...,0.652,1.6,3.0,4.6,1.1,1.7,0.3,1.2,2.7,8.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,472,Jeff Withey,11-12,C,23,NOP,58,4,11.8,1.2,...,0.712,0.8,1.7,2.6,0.4,0.3,0.9,0.3,1.3,3.3
480,478,Tony Wroten,11-12,PG,20,PHI,72,16,24.5,4.8,...,0.641,1.0,2.2,3.2,3.0,1.1,0.2,2.8,2.1,13.0
481,481,Cody Zeller,11-12,C,21,CHA,82,3,17.3,2.1,...,0.730,1.4,2.9,4.3,1.1,0.5,0.5,1.1,2.1,6.0
482,482,Tyler Zeller,11-12,C,24,CLE,70,9,15.0,2.2,...,0.719,1.5,2.6,4.0,0.5,0.3,0.5,0.9,2.0,5.7
483,488,James Young,11-12,SG,19,BOS,31,0,10.7,1.2,...,0.552,0.3,1.1,1.4,0.4,0.3,0.1,0.2,0.7,3.4

In [31]:
aggregation_functions = {'Rk': 'first', 'Season': 'first', 'Pos': 'first', 'Age': 'mean', 'Tm': 'first', 'G': 'mean', 'GS': 'mean', 'MP': 'mean', 'FG': 'mean',
       'FGA': 'mean', 'FG%': 'mean', '3P': 'mean', '3PA': 'mean', '3P%': 'mean', '2P': 'mean', '2PA': 'mean', '2P%': 'mean', 'eFG%': 'mean', 
        'FT': 'mean', 'FTA': 'mean', 'FT%': 'mean', 'ORB': 'mean', 'DRB': 'mean', 'TRB': 'mean', 'AST': 'mean', 'STL': 'mean',
        'BLK': 'mean', 'TOV': 'mean', 'PF': 'mean',
       'PTS': 'mean'}
df_new = new_s.groupby(new_s['Player']).aggregate(aggregation_functions)
df_new

,Rk,Season,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
Player,,,,,,,,,,,,,,,,,,,,,
Al Horford,207,15-16,C,27.0,ATL,54.4,54.4,32.88,6.90,12.74,...,0.7232,2.16,5.84,8.02,2.88,0.92,1.34,1.66,1.92,15.76
Al Jefferson,222,15-16,C,29.0,CHO,64.8,58.2,31.20,7.72,15.60,...,0.7076,1.80,7.08,8.88,1.92,0.80,1.22,1.14,2.34,17.48
Al-Farouq Aminu,11,15-16,SF,23.0,POR,75.6,48.4,24.44,2.76,6.30,...,0.7208,1.50,4.34,5.86,1.26,0.98,0.62,1.24,1.98,7.26
Alan Anderson,14,15-16,SG,31.0,WAS,49.4,11.8,22.24,2.70,6.90,...,0.8070,0.40,1.86,2.28,1.26,0.54,0.12,0.90,1.98,7.98
Alec Burks,70,15-16,SG,22.0,UTA,51.8,8.4,24.16,3.78,8.96,...,0.7524,0.72,2.40,3.10,2.00,0.62,0.16,1.50,2.06,11.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wesley Johnson,235,15-16,SF,26.0,LAC,70.0,43.0,24.08,3.10,7.54,...,0.7450,0.62,2.76,3.38,1.08,0.78,0.68,0.96,1.96,7.98
Wesley Matthews,282,15-16,SF,27.0,DAL,71.0,68.4,34.02,5.02,11.80,...,0.8218,0.56,2.70,3.30,2.16,1.20,0.22,1.28,2.26,14.66
Zach Randolph,368,15-16,PF,32.0,MEM,64.4,57.2,31.38,6.14,13.06,...,0.7424,3.22,6.34,9.52,1.98,0.78,0.24,1.88,2.34,15.16
Zaza Pachulia,341,15-16,C,29.0,DAL,62.4,43.2,25.04,2.82,6.08,...,0.7800,2.78,4.62,7.38,1.92,0.86,0.32,1.56,2.50,7.66
Ömer Aşık,26,15-16,C,27.0,NOP,68.0,48.6,21.66,2.32,4.44,...,0.5528,2.48,5.68,8.16,0.64,0.42,0.78,1.30,2.02,6.06

In [32]:
_12_to_16_with_sal = pd.merge(left=df_new, right=sixteen_salary, how='left', on='Player')

In [33]:
_12_to_16_with_sal

,Player,Rk,Season,Pos,Age,Tm,G,GS,MP,FG,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,salary
0,Al Horford,207,15-16,C,27.0,ATL,54.4,54.4,32.88,6.90,...,2.16,5.84,8.02,2.88,0.92,1.34,1.66,1.92,15.76,12000000.0
1,Al Jefferson,222,15-16,C,29.0,CHO,64.8,58.2,31.20,7.72,...,1.80,7.08,8.88,1.92,0.80,1.22,1.14,2.34,17.48,13500000.0
2,Al-Farouq Aminu,11,15-16,SF,23.0,POR,75.6,48.4,24.44,2.76,...,1.50,4.34,5.86,1.26,0.98,0.62,1.24,1.98,7.26,8042895.0
3,Alan Anderson,14,15-16,SG,31.0,WAS,49.4,11.8,22.24,2.70,...,0.40,1.86,2.28,1.26,0.54,0.12,0.90,1.98,7.98,4000000.0
4,Alec Burks,70,15-16,SG,22.0,UTA,51.8,8.4,24.16,3.78,...,0.72,2.40,3.10,2.00,0.62,0.16,1.50,2.06,11.08,9463484.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,Wesley Johnson,235,15-16,SF,26.0,LAC,70.0,43.0,24.08,3.10,...,0.62,2.76,3.38,1.08,0.78,0.68,0.96,1.96,7.98,1100602.0
234,Wesley Matthews,282,15-16,SF,27.0,DAL,71.0,68.4,34.02,5.02,...,0.56,2.70,3.30,2.16,1.20,0.22,1.28,2.26,14.66,16407500.0
235,Zach Randolph,368,15-16,PF,32.0,MEM,64.4,57.2,31.38,6.14,...,3.22,6.34,9.52,1.98,0.78,0.24,1.88,2.34,15.16,9638555.0
236,Zaza Pachulia,341,15-16,C,29.0,DAL,62.4,43.2,25.04,2.82,...,2.78,4.62,7.38,1.92,0.86,0.32,1.56,2.50,7.66,5200000.0
237,Ömer Aşık,26,15-16,C,27.0,NOP,68.0,48.6,21.66,2.32,...,2.48,5.68,8.16,0.64,0.42,0.78,1.30,2.02,6.06,NaN

In [34]:
s=pd.concat([seventeen_salary, sixteen_stats, fifteen_stats, fourteen_stats, thirteen_stats],axis=0)

In [35]:
new_s = s[s['Player'].map(s['Player'].value_counts()) == 5]
new_s

,Player,salary,Rk,Season,Pos,Age,Tm,G,GS,MP,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
5330,LeBron James,30963450.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5331,Chris Paul,22868827.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5332,Chandler Parsons,22116750.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5333,Bradley Beal,22116750.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5334,Anthony Davis,22116750.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,Nick Young,NaN,465.0,12-13,SG,27.0,PHI,59.0,17.0,23.9,...,0.820,0.4,1.8,2.2,1.4,0.6,0.2,0.8,1.4,10.6
465,Thaddeus Young,NaN,467.0,12-13,PF,24.0,PHI,76.0,76.0,34.6,...,0.574,2.4,5.1,7.5,1.6,1.8,0.7,1.2,2.5,14.8
467,Tyler Zeller,NaN,469.0,12-13,C,23.0,CLE,77.0,55.0,26.4,...,0.764,2.1,3.6,5.7,1.2,0.5,0.9,1.2,3.3,7.9
471,Cody Zeller,NaN,481.0,12-13,C,21.0,CHA,82.0,3.0,17.3,...,0.730,1.4,2.9,4.3,1.1,0.5,0.5,1.1,2.1,6.0
472,James Young,NaN,488.0,12-13,SG,19.0,BOS,31.0,0.0,10.7,...,0.552,0.3,1.1,1.4,0.4,0.3,0.1,0.2,0.7,3.4

In [36]:
aggregation_functions = {'Rk': 'first', 'Season': 'first', 'Pos': 'first', 'Age': 'mean', 'Tm': 'first', 'G': 'mean', 'GS': 'mean', 'MP': 'mean', 'FG': 'mean',
       'FGA': 'mean', 'FG%': 'mean', '3P': 'mean', '3PA': 'mean', '3P%': 'mean', '2P': 'mean', '2PA': 'mean', '2P%': 'mean', 'eFG%': 'mean', 
        'FT': 'mean', 'FTA': 'mean', 'FT%': 'mean', 'ORB': 'mean', 'DRB': 'mean', 'TRB': 'mean', 'AST': 'mean', 'STL': 'mean',
        'BLK': 'mean', 'TOV': 'mean', 'PF': 'mean',
       'PTS': 'mean'}
df_new = new_s.groupby(new_s['Player']).aggregate(aggregation_functions)
df_new

,Rk,Season,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
Player,,,,,,,,,,,,,,,,,,,,,
Aaron Brooks,62.0,15-16,PG,29.5,CHI,69.00,13.25,19.875,3.200,7.725,...,0.81050,0.375,1.350,1.725,2.800,0.600,0.175,1.500,2.000,8.700
Al Horford,207.0,15-16,C,27.5,ATL,65.25,65.25,33.200,7.325,13.575,...,0.72075,2.100,6.150,8.275,3.050,0.925,1.350,1.700,1.925,16.600
Al Jefferson,222.0,15-16,C,29.5,CHO,65.75,57.50,30.500,7.525,15.200,...,0.69100,1.700,7.000,8.700,1.850,0.800,1.100,1.175,2.300,17.050
Al-Farouq Aminu,11.0,15-16,SF,23.5,POR,78.00,55.25,24.950,2.875,6.500,...,0.71250,1.525,4.625,6.150,1.325,1.000,0.650,1.200,1.950,7.575
Alec Burks,70.0,15-16,SG,22.5,UTA,50.00,10.50,26.225,4.075,9.675,...,0.75875,0.650,2.675,3.325,2.275,0.650,0.175,1.650,2.225,12.050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wayne Ellington,129.0,15-16,SG,26.5,BRK,66.00,24.75,19.275,2.725,6.625,...,0.87150,0.325,1.850,2.150,1.100,0.525,0.025,0.575,1.000,7.200
Wesley Johnson,235.0,15-16,SF,26.5,LAC,71.25,37.75,24.450,3.275,7.900,...,0.75475,0.675,2.850,3.550,1.125,0.850,0.675,0.975,2.000,8.475
Wesley Matthews,282.0,15-16,SF,27.5,DAL,72.25,72.25,34.075,5.075,11.850,...,0.81225,0.500,2.750,3.275,2.275,1.125,0.225,1.325,2.275,14.900
Will Barton,36.0,15-16,SG,23.5,DEN,63.50,1.50,16.800,2.750,6.525,...,0.79375,0.500,2.575,3.100,1.375,0.600,0.275,1.000,1.150,7.300
Zach Randolph,368.0,15-16,PF,32.5,MEM,73.50,69.50,32.650,6.500,13.775,...,0.76325,3.325,6.600,9.900,2.050,0.775,0.275,2.000,2.425,16.050

In [37]:
_13_to_17_with_sal = pd.merge(left=df_new, right=seventeen_salary, how='left', on='Player')

In [38]:
_13_to_17_with_sal

,Player,Rk,Season,Pos,Age,Tm,G,GS,MP,FG,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,salary
0,Aaron Brooks,62.0,15-16,PG,29.5,CHI,69.00,13.25,19.875,3.200,...,0.375,1.350,1.725,2.800,0.600,0.175,1.500,2.000,8.700,2700000.0
1,Al Horford,207.0,15-16,C,27.5,ATL,65.25,65.25,33.200,7.325,...,2.100,6.150,8.275,3.050,0.925,1.350,1.700,1.925,16.600,26540100.0
2,Al Jefferson,222.0,15-16,C,29.5,CHO,65.75,57.50,30.500,7.525,...,1.700,7.000,8.700,1.850,0.800,1.100,1.175,2.300,17.050,10314532.0
3,Al-Farouq Aminu,11.0,15-16,SF,23.5,POR,78.00,55.25,24.950,2.875,...,1.525,4.625,6.150,1.325,1.000,0.650,1.200,1.950,7.575,7680965.0
4,Alec Burks,70.0,15-16,SG,22.5,UTA,50.00,10.50,26.225,4.075,...,0.650,2.675,3.325,2.275,0.650,0.175,1.650,2.225,12.050,10154495.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,Wayne Ellington,129.0,15-16,SG,26.5,BRK,66.00,24.75,19.275,2.725,...,0.325,1.850,2.150,1.100,0.525,0.025,0.575,1.000,7.200,6000000.0
194,Wesley Johnson,235.0,15-16,SF,26.5,LAC,71.25,37.75,24.450,3.275,...,0.675,2.850,3.550,1.125,0.850,0.675,0.975,2.000,8.475,5628000.0
195,Wesley Matthews,282.0,15-16,SF,27.5,DAL,72.25,72.25,34.075,5.075,...,0.500,2.750,3.275,2.275,1.125,0.225,1.325,2.275,14.900,17145838.0
196,Will Barton,36.0,15-16,SG,23.5,DEN,63.50,1.50,16.800,2.750,...,0.500,2.575,3.100,1.375,0.600,0.275,1.000,1.150,7.300,3533333.0
197,Zach Randolph,368.0,15-16,PF,32.5,MEM,73.50,69.50,32.650,6.500,...,3.325,6.600,9.900,2.050,0.775,0.275,2.000,2.425,16.050,10361445.0

In [39]:
s=pd.concat([eighteen_salary, seventeen_salary, sixteen_stats, fifteen_stats, fourteen_stats],axis=0)

In [40]:
new_s = s[s['Player'].map(s['Player'].value_counts()) == 5]
new_s

,Player,salary,Rk,Season,Pos,Age,Tm,G,GS,MP,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
5792,Stephen Curry,37457154.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5793,Al Horford,27734406.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5794,Carmelo Anthony,26243760.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5795,Damian Lillard,26153057.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5797,Jrue Holiday,25686667.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,Tony Wroten,NaN,478.0,13-14,PG,20.0,PHI,72.0,16.0,24.5,...,0.641,1.0,2.2,3.2,3.0,1.1,0.2,2.8,2.1,13.0
477,Nick Young,NaN,479.0,13-14,SG,28.0,LAL,64.0,9.0,28.3,...,0.825,0.5,2.1,2.6,1.5,0.7,0.2,1.5,2.4,17.9
478,Thaddeus Young,NaN,480.0,13-14,PF,25.0,PHI,79.0,78.0,34.4,...,0.712,2.1,3.9,6.0,2.3,2.1,0.5,2.1,2.7,17.9
479,Cody Zeller,NaN,481.0,13-14,C,21.0,CHA,82.0,3.0,17.3,...,0.730,1.4,2.9,4.3,1.1,0.5,0.5,1.1,2.1,6.0
480,Tyler Zeller,NaN,482.0,13-14,C,24.0,CLE,70.0,9.0,15.0,...,0.719,1.5,2.6,4.0,0.5,0.3,0.5,0.9,2.0,5.7

In [41]:
aggregation_functions = {'Rk': 'first', 'Season': 'first', 'Pos': 'first', 'Age': 'mean', 'Tm': 'first', 'G': 'mean', 'GS': 'mean', 'MP': 'mean', 'FG': 'mean',
       'FGA': 'mean', 'FG%': 'mean', '3P': 'mean', '3PA': 'mean', '3P%': 'mean', '2P': 'mean', '2PA': 'mean', '2P%': 'mean', 'eFG%': 'mean', 
        'FT': 'mean', 'FTA': 'mean', 'FT%': 'mean', 'ORB': 'mean', 'DRB': 'mean', 'TRB': 'mean', 'AST': 'mean', 'STL': 'mean',
        'BLK': 'mean', 'TOV': 'mean', 'PF': 'mean',
       'PTS': 'mean'}
df_new = new_s.groupby(new_s['Player']).aggregate(aggregation_functions)
df_new

,Rk,Season,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
Player,,,,,,,,,,,,,,,,,,,,,
Al Horford,207.0,15-16,C,28.0,ATL,62.333333,62.333333,31.866667,7.166667,13.333333,...,0.746333,1.933333,5.666667,7.633333,3.000000,0.866667,1.433333,1.600000,1.833333,16.333333
Al Jefferson,222.0,15-16,C,30.0,CHO,61.666667,50.666667,29.633333,7.433333,15.000000,...,0.664667,1.600000,6.933333,8.533333,1.766667,0.733333,1.100000,1.133333,2.333333,16.800000
Al-Farouq Aminu,11.0,15-16,SF,24.0,POR,78.666667,50.000000,24.200000,2.833333,6.600000,...,0.704333,1.433333,4.200000,5.633333,1.300000,0.933333,0.633333,1.100000,1.933333,7.666667
Alec Burks,70.0,15-16,SG,23.0,UTA,45.333333,14.000000,29.033333,4.600000,10.866667,...,0.774000,0.666667,3.000000,3.666667,2.566667,0.700000,0.166667,1.800000,2.366667,13.733333
Alex Len,262.0,15-16,C,21.0,PHO,63.000000,31.000000,17.966667,2.266667,5.000000,...,0.691667,1.766667,3.733333,5.533333,0.600000,0.366667,0.900000,1.200000,2.533333,5.766667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vince Carter,80.0,15-16,SG,38.0,MEM,69.000000,1.333333,19.233333,2.766667,7.300000,...,0.814333,0.566667,2.066667,2.633333,1.566667,0.700000,0.300000,0.866667,1.933333,8.100000
Wesley Johnson,235.0,15-16,SF,27.0,LAC,78.333333,43.333333,26.233333,3.300000,7.900000,...,0.749333,0.766667,3.133333,3.900000,1.266667,1.000000,0.766667,0.966667,2.300000,8.633333
Wesley Matthews,282.0,15-16,SF,28.0,DAL,73.333333,73.333333,33.833333,5.066667,11.900000,...,0.817333,0.500000,2.900000,3.433333,2.200000,1.066667,0.200000,1.233333,2.200000,14.933333
Will Barton,36.0,15-16,SG,24.0,DEN,60.333333,0.333333,18.333333,3.133333,7.300000,...,0.802000,0.500000,2.933333,3.466667,1.566667,0.633333,0.333333,1.066667,1.266667,8.400000
Zach Randolph,368.0,15-16,PF,33.0,MEM,72.666667,67.666667,32.100000,6.600000,13.866667,...,0.767667,3.066667,6.400000,9.466667,2.266667,0.766667,0.233333,2.000000,2.433333,16.266667

In [42]:
_14_to_18_with_sal = pd.merge(left=df_new, right=eighteen_salary, how='left', on='Player')
_14_to_18_with_sal.head()

,Player,Rk,Season,Pos,Age,Tm,G,GS,MP,FG,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,salary
0,Al Horford,207.0,15-16,C,28.0,ATL,62.333333,62.333333,31.866667,7.166667,...,1.933333,5.666667,7.633333,3.000000,0.866667,1.433333,1.600000,1.833333,16.333333,27734406.0
1,Al Jefferson,222.0,15-16,C,30.0,CHO,61.666667,50.666667,29.633333,7.433333,...,1.600000,6.933333,8.533333,1.766667,0.733333,1.100000,1.133333,2.333333,16.800000,10000000.0
2,Al-Farouq Aminu,11.0,15-16,SF,24.0,POR,78.666667,50.000000,24.200000,2.833333,...,1.433333,4.200000,5.633333,1.300000,0.933333,0.633333,1.100000,1.933333,7.666667,7319035.0
3,Alec Burks,70.0,15-16,SG,23.0,UTA,45.333333,14.000000,29.033333,4.600000,...,0.666667,3.000000,3.666667,2.566667,0.700000,0.166667,1.800000,2.366667,13.733333,10845506.0
4,Alex Len,262.0,15-16,C,21.0,PHO,63.000000,31.000000,17.966667,2.266667,...,1.766667,3.733333,5.533333,0.600000,0.366667,0.900000,1.200000,2.533333,5.766667,4187599.0

In [43]:
_11_to_15_with_sal.isnull().sum()

Player     0
Rk         0
Season     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         0
FGA        0
FG%        0
3P         0
3PA        0
3P%        5
2P         0
2PA        0
2P%        0
eFG%       0
FT         0
FTA        0
FT%        0
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
salary    51
dtype: int64

In [44]:
_12_to_16_with_sal.isnull().sum()

Player     0
Rk         0
Season     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         0
FGA        0
FG%        0
3P         0
3PA        0
3P%        4
2P         0
2PA        0
2P%        0
eFG%       0
FT         0
FTA        0
FT%        0
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
salary    48
dtype: int64

In [45]:
_13_to_17_with_sal.isnull().sum()

Player    0
Rk        0
Season    0
Pos       0
Age       0
Tm        0
G         0
GS        0
MP        0
FG        0
FGA       0
FG%       0
3P        0
3PA       0
3P%       4
2P        0
2PA       0
2P%       0
eFG%      0
FT        0
FTA       0
FT%       0
ORB       0
DRB       0
TRB       0
AST       0
STL       0
BLK       0
TOV       0
PF        0
PTS       0
salary    0
dtype: int64

In [46]:
_14_to_18_with_sal.isnull().sum()

Player    0
Rk        0
Season    0
Pos       0
Age       0
Tm        0
G         0
GS        0
MP        0
FG        0
FGA       0
FG%       0
3P        0
3PA       0
3P%       4
2P        0
2PA       0
2P%       0
eFG%      0
FT        0
FTA       0
FT%       0
ORB       0
DRB       0
TRB       0
AST       0
STL       0
BLK       0
TOV       0
PF        0
PTS       0
salary    0
dtype: int64

In [47]:
_14_to_18_with_sal = _14_to_18_with_sal.dropna()

In [48]:
_14_to_18_with_sal.isnull().sum()

Player    0
Rk        0
Season    0
Pos       0
Age       0
Tm        0
G         0
GS        0
MP        0
FG        0
FGA       0
FG%       0
3P        0
3PA       0
3P%       0
2P        0
2PA       0
2P%       0
eFG%      0
FT        0
FTA       0
FT%       0
ORB       0
DRB       0
TRB       0
AST       0
STL       0
BLK       0
TOV       0
PF        0
PTS       0
salary    0
dtype: int64

In [49]:
_13_to_17_with_sal = _13_to_17_with_sal.dropna()

In [50]:
_11_to_15_with_sal.to_csv('./datasets/eleven_to_fifteen_with_sal.csv', index = False)
_12_to_16_with_sal.to_csv('./datasets/twelve_to_sixteen_with_sal.csv', index = False)
_13_to_17_with_sal.to_csv('./datasets/thirteen_to_seventeen_with_sal.csv', index = False)
_14_to_18_with_sal.to_csv('./datasets/fourteen_to_eighteen_with_sal.csv', index = False)

In [51]:
_14_to_18_with_sal.describe()

,Rk,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,salary
count,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,...,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,1.750000e+02
mean,229.217143,26.074286,64.927619,38.200000,25.281333,4.094667,9.058857,0.450552,0.903238,2.504190,...,1.065905,3.391238,4.454476,2.436952,0.833905,0.500000,1.461143,2.020762,11.019238,1.142361e+07
std,133.559831,3.607172,13.050001,26.115179,6.988884,1.879355,4.037398,0.056156,0.721683,1.851711,...,0.851900,1.752061,2.486565,1.902443,0.413215,0.487336,0.735985,0.542963,5.117107,7.995105e+06
min,3.000000,20.000000,16.000000,0.333333,8.733333,0.933333,2.433333,0.262667,0.000000,0.000000,...,0.066667,0.833333,0.933333,0.200000,0.133333,0.000000,0.233333,0.633333,2.633333,5.767200e+04
25%,116.500000,23.000000,58.666667,13.166667,19.450000,2.700000,5.616667,0.417000,0.316667,1.033333,...,0.466667,2.066667,2.600000,1.133333,0.566667,0.183333,0.900000,1.633333,7.033333,5.096000e+06
50%,225.000000,26.000000,68.333333,36.666667,26.066667,3.566667,7.966667,0.438000,0.833333,2.466667,...,0.733333,3.033333,3.800000,1.766667,0.766667,0.333333,1.333333,2.033333,9.966667,1.000000e+07
75%,338.500000,28.000000,75.500000,62.666667,31.450000,5.683333,12.033333,0.472333,1.383333,3.750000,...,1.450000,4.216667,5.633333,3.266667,1.000000,0.616667,1.833333,2.383333,14.800000,1.739728e+07
max,476.000000,38.000000,82.000000,81.000000,38.100000,8.933333,19.900000,0.696333,4.000000,9.066667,...,4.100000,9.966667,14.133333,10.300000,2.166667,2.566667,3.866667,3.833333,25.966667,3.745715e+07