In [233]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
#imports

In [234]:
salaries_03_to_18 = pd.read_csv('./datasets/NBASalaryData03-17.csv')
twenty_salary_cond = pd.read_csv('./datasets/twenty_salary_cond.csv')

In [235]:
eleven_salary = salaries_03_to_18[salaries_03_to_18.season == '2010-2011']
twelve_salary = salaries_03_to_18[salaries_03_to_18.season == '2011-2012']
thirtheen_salary = salaries_03_to_18[salaries_03_to_18.season == '2012-2013']
fourteen_salary = salaries_03_to_18[salaries_03_to_18.season == '2013-2014']
fifteen_salary = salaries_03_to_18[salaries_03_to_18.season == '2014-2015']
sixteen_salary = salaries_03_to_18[salaries_03_to_18.season == '2015-2016']
seventeen_salary = salaries_03_to_18[salaries_03_to_18.season == '2016-2017']
eighteen_salary = salaries_03_to_18[salaries_03_to_18.season == '2017-2018']

In [236]:
eleven_salary.to_csv('./datasets/eleven_salary.csv', index = False)
twelve_salary.to_csv('./datasets/twelve_salary.csv', index = False)
thirtheen_salary.to_csv('./datasets/thirtheen_salary.csv', index = False)
fourteen_salary.to_csv('./datasets/fourteen_salary.csv', index = False)
fifteen_salary.to_csv('./datasets/fifteen_salary.csv', index = False)
sixteen_salary.to_csv('./datasets/sixteen_salary.csv', index = False)
seventeen_salary.to_csv('./datasets/seventeen_salary.csv', index = False)
eighteen_salary.to_csv('./datasets/eighteen_salary.csv', index = False)

In [237]:
twenty_stats = pd.read_csv('./datasets/twenty_STATS.csv')
nineteen_stats = pd.read_csv('./datasets/nineteen_STATS.csv')
eighteen_stats =  pd.read_csv('./datasets/eighteen_STATS.csv')
seventeen_stats = pd.read_csv('./datasets/seventeen_STATS.csv')
sixteen_stats = pd.read_csv('./datasets/sixteen_STATS.csv')
fifteen_stats = pd.read_csv('./datasets/fifteen_STATS.csv')
fourteen_stats = pd.read_csv('./datasets/fourteen_STATS.csv')
thirteen_stats = pd.read_csv('./datasets/thirteen_STATS.csv')
twelve_stats = pd.read_csv('./datasets/twelve_STATS.csv')
eleven_stats = pd.read_csv('./datasets/eleven_STATS.csv')

In [238]:
s=pd.concat([twenty_stats,nineteen_stats,eighteen_stats,seventeen_stats],axis=0)

In [239]:
new_s = s[s['Player'].map(s['Player'].value_counts()) == 4]
new_s

#Here, we are grouping by players who are in all five of our datasets
#The next step will be to take their averages from the five seasons

,Rk,Player,Season,Pos,Age,Tm,G,GS,MP,FG,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1.0,Steven Adams,19-20,C,26.0,OKC,63.0,63.0,26.7,4.5,...,0.582,3.3,6.0,9.3,2.3,0.8,1.1,1.5,1.9,10.9
2,3.0,LaMarcus Aldridge,19-20,C,34.0,SAS,53.0,53.0,33.1,7.4,...,0.827,1.9,5.5,7.4,2.4,0.7,1.6,1.4,2.4,18.9
8,9.0,Al-Farouq Aminu,19-20,PF,29.0,ORL,18.0,2.0,21.1,1.4,...,0.655,1.3,3.5,4.8,1.2,1.0,0.4,0.9,1.5,4.3
9,10.0,Justin Anderson,19-20,SF,26.0,BRK,10.0,1.0,10.7,1.0,...,0.500,0.1,2.0,2.1,0.8,0.0,0.6,0.4,1.3,2.8
10,11.0,Kyle Anderson,19-20,PF,26.0,MEM,67.0,28.0,19.9,2.3,...,0.667,0.9,3.4,4.3,2.4,0.8,0.6,1.0,1.7,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,477.0,Delon Wright,16-17,PG,24.0,TOR,27.0,0.0,16.5,1.8,...,0.764,0.6,1.2,1.8,2.1,1.0,0.4,0.9,1.1,5.6
480,481.0,Thaddeus Young,16-17,PF,28.0,IND,74.0,74.0,30.2,4.9,...,0.523,1.8,4.3,6.1,1.6,1.5,0.4,1.3,1.8,11.0
481,482.0,Cody Zeller,16-17,C,24.0,CHO,62.0,58.0,27.8,4.1,...,0.679,2.2,4.4,6.5,1.6,1.0,0.9,1.0,3.0,10.3
482,483.0,Tyler Zeller,16-17,C,27.0,BOS,51.0,5.0,10.3,1.5,...,0.564,0.8,1.6,2.4,0.8,0.1,0.4,0.4,1.2,3.5
485,486.0,Ivica Zubac,16-17,C,19.0,LAL,38.0,11.0,16.0,3.3,...,0.653,1.1,3.1,4.2,0.8,0.4,0.9,0.8,1.7,7.5

In [240]:
new_s.dtypes

Rk        float64
Player     object
Season     object
Pos        object
Age       float64
Tm         object
G         float64
GS        float64
MP        float64
FG        float64
FGA       float64
FG%       float64
3P        float64
3PA       float64
3P%       float64
2P        float64
2PA       float64
2P%       float64
eFG%      float64
FT        float64
FTA       float64
FT%       float64
ORB       float64
DRB       float64
TRB       float64
AST       float64
STL       float64
BLK       float64
TOV       float64
PF        float64
PTS       float64
dtype: object

In [212]:
aggregation_functions = {'Rk': 'first', 'Season': 'first', 'Pos': 'first', 'Age': 'mean', 'Tm': 'first', 'G': 'mean', 'GS': 'mean', 'MP': 'mean', 'FG': 'mean',
       'FGA': 'mean', 'FG%': 'mean', '3P': 'mean', '3PA': 'mean', '3P%': 'mean', '2P': 'mean', '2PA': 'mean', '2P%': 'mean', 'eFG%': 'mean', 
        'FT': 'mean', 'FTA': 'mean', 'FT%': 'mean', 'ORB': 'mean', 'DRB': 'mean', 'TRB': 'mean', 'AST': 'mean', 'STL': 'mean',
        'BLK': 'mean', 'TOV': 'mean', 'PF': 'mean',
       'PTS': 'mean'}
df_new = new_s.groupby(new_s['Player']).aggregate(aggregation_functions)
df_new
#Finding averages of all of the players over this five year span

,Rk,Season,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
Player,,,,,,,,,,,,,,,,,,,,,
Aaron Gordon,178.0,19-20,PF,22.5,ORL,69.50,67.25,31.975,5.700,12.875,...,0.70550,1.600,5.400,7.025,2.900,0.825,0.650,1.650,2.075,15.175
Al Horford,228.0,19-20,C,31.5,PHI,68.75,67.25,30.775,5.300,10.875,...,0.79175,1.525,5.400,6.925,4.475,0.775,1.150,1.550,1.975,13.100
Al-Farouq Aminu,9.0,19-20,PF,27.5,ORL,57.25,43.75,27.125,2.725,7.025,...,0.74150,1.350,5.475,6.825,1.325,0.975,0.525,1.100,1.750,7.925
Alec Burks,80.0,19-20,SG,26.5,TOT,59.00,11.00,20.025,3.250,7.850,...,0.83550,0.475,2.975,3.475,1.650,0.625,0.200,1.025,1.425,9.550
Alex Len,293.0,19-20,C,24.5,TOT,69.50,22.50,19.550,3.375,6.425,...,0.67525,2.100,4.275,6.350,0.950,0.425,1.000,1.175,2.575,8.900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Willie Cauley-Stein,94.0,19-20,C,24.5,TOT,70.75,49.75,23.625,4.250,7.925,...,0.61125,1.675,4.750,6.425,1.800,0.975,0.800,1.025,2.375,10.000
Willy Hernangómez,214.0,19-20,C,23.5,CHO,52.25,6.50,13.700,2.575,4.875,...,0.67625,1.775,3.325,5.125,0.975,0.400,0.325,1.025,1.525,6.675
Wilson Chandler,96.0,19-20,SF,30.5,BRK,57.75,35.00,26.675,3.550,8.075,...,0.77225,1.025,4.025,5.050,1.700,0.575,0.400,1.175,2.300,9.400
Yogi Ferrell,156.0,19-20,PG,24.5,SAC,62.25,13.25,19.850,2.775,6.575,...,0.84500,0.250,1.750,1.975,2.375,0.650,0.125,0.925,1.400,7.625
Zach LaVine,286.0,19-20,SG,22.5,CHI,48.50,48.25,33.450,7.500,16.975,...,0.82075,0.525,3.650,4.200,3.675,1.100,0.325,2.600,2.225,21.200

In [213]:
_17_to_20_with_sal = pd.merge(left=df_new, right=twenty_salary_cond, how='left', on='Player')

In [214]:
_17_to_20_with_sal['Player'].duplicated().value_counts()

False    260
True      28
Name: Player, dtype: int64

In [215]:
_17_to_20_with_sal = _17_to_20_with_sal.drop_duplicates(subset=['Player'], keep='first')
_17_to_20_with_sal.head()

,Player,Rk,Season,Pos,Age,Tm,G,GS,MP,FG,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,2019-20
0,Aaron Gordon,178.0,19-20,PF,22.5,ORL,69.50,67.25,31.975,5.700,...,1.600,5.400,7.025,2.900,0.825,0.650,1.650,2.075,15.175,"$19,863,636"
1,Al Horford,228.0,19-20,C,31.5,PHI,68.75,67.25,30.775,5.300,...,1.525,5.400,6.925,4.475,0.775,1.150,1.550,1.975,13.100,"$28,000,000"
2,Al-Farouq Aminu,9.0,19-20,PF,27.5,ORL,57.25,43.75,27.125,2.725,...,1.350,5.475,6.825,1.325,0.975,0.525,1.100,1.750,7.925,"$9,258,000"
3,Alec Burks,80.0,19-20,SG,26.5,TOT,59.00,11.00,20.025,3.250,...,0.475,2.975,3.475,1.650,0.625,0.200,1.025,1.425,9.550,"$2,320,044"
4,Alex Len,293.0,19-20,C,24.5,TOT,69.50,22.50,19.550,3.375,...,2.100,4.275,6.350,0.950,0.425,1.000,1.175,2.575,8.900,"$4,160,000"

In [216]:
_17_to_20_with_sal.isnull().sum()

Player     0
Rk         0
Season     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         0
FGA        0
FG%        0
3P         0
3PA        0
3P%        0
2P         0
2PA        0
2P%        0
eFG%       0
FT         0
FTA        0
FT%        0
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
2019-20    8
dtype: int64

In [217]:
_17_to_20_with_sal = _17_to_20_with_sal.dropna()

In [218]:
_17_to_20_with_sal.shape

(252, 32)

In [219]:
_17_to_20_with_sal['2019-20'] = _17_to_20_with_sal['2019-20'].str.replace(',', '')
#Taking steps to turn column into integer

In [220]:
_17_to_20_with_sal['2019-20'] = _17_to_20_with_sal['2019-20'].str.replace('$', '')

In [221]:
_17_to_20_with_sal['2019-20'] = _17_to_20_with_sal['2019-20'].astype(int)
#Turning salary into an integer

In [222]:
_17_to_20_with_sal.corr()['2019-20'].sort_values(ascending=False)

2019-20    1.000000
PTS        0.769917
FG         0.756655
FGA        0.744345
MP         0.728757
FT         0.711148
FTA        0.701033
GS         0.690506
2PA        0.682875
TOV        0.682009
2P         0.669511
AST        0.591008
STL        0.560910
DRB        0.559780
TRB        0.487346
3PA        0.447394
3P         0.438508
PF         0.373891
G          0.303399
BLK        0.300565
FT%        0.266914
ORB        0.243670
3P%        0.125528
eFG%       0.104810
FG%        0.101789
Age        0.088307
2P%        0.084514
Rk        -0.007524
Name: 2019-20, dtype: float64

In [223]:
_17_to_20_with_sal.to_csv('./datasets/seventeen_to_twenty_with_sal.csv', index=False)

In [224]:
def condense_salary(year):
    year = year[['player', 'salary']]
    
    return year

In [225]:
eleven_stats.dtypes

Rk          int64
Player     object
Season     object
Pos        object
Age         int64
Tm         object
G           int64
GS          int64
MP        float64
FG        float64
FGA       float64
FG%       float64
3P        float64
3PA       float64
3P%       float64
2P        float64
2PA       float64
2P%       float64
eFG%      float64
FT        float64
FTA       float64
FT%       float64
ORB       float64
DRB       float64
TRB       float64
AST       float64
STL       float64
BLK       float64
TOV       float64
PF        float64
PTS       float64
dtype: object

In [226]:
eleven_salary = condense_salary(eleven_salary)
twelve_salary = condense_salary(twelve_salary)
thirtheen_salary = condense_salary(thirtheen_salary)
fourteen_salary = condense_salary(fourteen_salary)
fifteen_salary = condense_salary(fifteen_salary)
sixteen_salary = condense_salary(sixteen_salary)
seventeen_salary = condense_salary(seventeen_salary)
eighteen_salary = condense_salary(eighteen_salary)

In [227]:
# #This will make it easier to merge with stats
# eleven_salary = eleven_salary.rename(columns={'player': 'Player'})
# twelve_salary = twelve_salary.rename(columns={'player': 'Player'})
# thirtheen_salary = thirtheen_salary.rename(columns={'player': 'Player'})
# fourteen_salary = fourteen_salary.rename(columns={'player': 'Player'})
# fifteen_salary = fifteen_salary.rename(columns={'player': 'Player'})
# sixteen_salary = sixteen_salary.rename(columns={'player': 'Player'})
# seventeen_salary = seventeen_salary.rename(columns={'player': 'Player'})
# eighteen_salary = eighteen_salary.rename(columns={'player': 'Player'})

In [241]:
s=pd.concat([fifteen_stats, fourteen_stats, thirteen_stats, twelve_stats, eleven_stats],axis=0)

In [242]:
new_s = s[s['Player'].map(s['Player'].value_counts()) == 5]
new_s

,Rk,Player,Season,Pos,Age,Tm,G,GS,MP,FG,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
3,4,Jeff Adrien,14-15,PF,28,MIN,17,0,12.6,1.1,...,0.579,1.4,3.2,4.5,0.9,0.2,0.5,0.5,1.8,3.5
4,5,Arron Afflalo,14-15,SG,29,TOT,78,72,32.1,4.8,...,0.843,0.3,2.8,3.2,1.7,0.5,0.1,1.5,2.1,13.3
5,6,Alexis Ajinça,14-15,C,26,NOP,68,8,14.1,2.7,...,0.818,1.5,3.1,4.6,0.7,0.3,0.8,1,2.2,6.5
7,8,Cole Aldrich,14-15,C,26,NYK,61,16,16,2.4,...,0.781,1.7,3.9,5.5,1.2,0.6,1.1,1,2,5.5
8,9,LaMarcus Aldridge,14-15,PF,29,POR,71,71,35.4,9.3,...,0.845,2.5,7.7,10.2,1.7,0.7,1,1.7,1.8,23.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613,444,Terrence Williams,10-11,SG,23,NJN,10,0,20.6,2.9,...,0.5,0.3,3.3,3.6,3.1,0.5,0,2.5,2.1,6.7
614,444,Terrence Williams,10-11,SG,23,HOU,11,0,7.6,1.3,...,0.818,0.1,1.3,1.4,0.6,0.4,0,0.7,0.4,3.5
620,448,Dorell Wright,10-11,SF,25,GSW,82,82,38.4,5.9,...,0.789,1.1,4.2,5.3,3,1.5,0.8,1.6,2.1,16.4
622,450,Nick Young,10-11,SG,25,WAS,64,40,31.8,6.4,...,0.816,0.4,2.3,2.7,1.2,0.7,0.3,1.4,2.3,17.4
624,452,Thaddeus Young,10-11,PF,22,PHI,82,1,26,5.6,...,0.707,1.9,3.4,5.3,1,1.1,0.3,1.2,2.1,12.7

In [230]:
# new_s[['Rk', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG',
#        'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 
#         'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL',
#         'BLK', 'TOV', 'PF', 'PTS']] = new_s[['Rk', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG',
#        'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 
#         'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL',
#         'BLK', 'TOV', 'PF',
#        'PTS']].astype(float)